<?php
// $Id$

/**
* @file
* Module for custom pages for Lagervarer.dk.
*/


/** 
 * Implementation of hook_menu().
 */
function lv_pages_menu() {
	return array(
		'custom-front-page' => array(
			'type' => MENU_CALLBACK,
			'page callback' => 'lv_pages_front_page',
			'access arguments' => array('access content'),
		),
		'lagersalg' => array(
			'type' => MENU_CALLBACK,        
			'page callback' => 'lv_pages_lagersalg_page',
		    'access arguments' => array('access content'),
		),        	
		'information' => array(
			'type' => MENU_CALLBACK,
			'page callback' => 'lv_pages_information',
			'access arguments' => array('access content'),
		),		 
		'community' => array(
			'type' => MENU_CALLBACK,
			'page callback' => 'lv_pages_forum',
			'access arguments' => array('access content'),
		),
	);        	 
}        										


           

/**
 * Implementation of hook_block().
 */                               
function lv_pages_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
    
    	case 'list':
        	$blocks[0]['info'] = t('Front page right: New nodes');
        	$blocks[1]['info'] = t('Top bloggers');            
        	$blocks[2]['info'] = t('Lagersalg right: New nodes');
        	$blocks[3]['info'] = t('Lagersalg right: Seller Portraits');            
            return $blocks;
            break;
		case 'view':
        	switch ($delta) {
            case 0:
				$blocks['subject'] = t("What's new");            
				
				$result = db_query("SELECT n.nid, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 AND n.type IN ('page', 'story') ORDER BY n.created DESC LIMIT 0,5");

				$output = '';
				while ($node = db_fetch_object($result)) {
					$node = node_load($node->nid);
					if (!$node->field_consumer_front[0]['value']) {                    
	                    $output .= '<div id="lv-teaser-'.$node->nid.'" class="lv-teaser"><h2>'.$node->title.'</h2>';
    	                if (isset($node->field_image[0])) {
	    	                $output .= '<div class="lv-teaser-image"><a href="'.url('node/'.$node->nid).'">'.theme('imagecache', 'sidebar', $node->field_image[0]['filepath'], $node->field_image[0]['data']['alt']).'</a></div>';
						}
                	    $output .= '<div class="lv-teaser-content">'.$node->field_teaser[0]['value'].'</div><div class="lv-teaser-link">'.l(t('Read more'), 'node/'.$node->nid).'</div></div>';                        
					}                        
				}                                
		    
              	$blocks['content'] = $output;
             	break;
			case 1:
            	$blocks['subject'] = t('Top Bloggers');                
				$result = db_query("SELECT DISTINCT(n.uid), n.nid, n.created FROM {node} n WHERE n.status = 1 AND n.type = ('blog') AND n.uid IN (14) ORDER BY n.created DESC");                

				$output = '';
				while ($node = db_fetch_object($result)) {
					$node = node_load($node->nid);
                    $output = '<div id="lv-teaser-'.$node->nid.'" class="lv-teaser"><h2>'.$node->title.'</h2>';
                    if (isset($node->field_image_cache[0])) {
	                    $output .= '<div class="lv-teaser-image"><a href="'.url('node/'.$node->nid).'">'.theme('imagecache', 'sidebar', $node->field_image_cache[0]['filepath'], $node->field_image_cache[0]['data']['alt']).'</a></div>';
					}
                    $output .= '<div class="lv-teaser-content">'.lv_pages_trim($node->body, 200).'</div><div class="lv-teaser-link">'.l(t('Read more'), 'node/'.$node->nid).'</div></div>';                        
				}                                
		    
              	$blocks['content'] = $output;
             	break;                
            case 2:
				$blocks['subject'] = t("What's new");            
				
				$result = db_query("SELECT n.nid, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 AND n.type IN ('page', 'story') ORDER BY n.created DESC LIMIT 0,5");

				$output = '';
				while ($node = db_fetch_object($result)) {
					$node = node_load($node->nid);
					if ($node->field_consumer_front[0]['value']) {
    	                $output .= '<div id="lv-teaser-'.$node->nid.'" class="lv-teaser"><h2>'.$node->title.'</h2>';
        	            if (isset($node->field_image[0])) {
	        	            $output .= '<div class="lv-teaser-image"><a href="'.url('node/'.$node->nid).'">'.theme('imagecache', 'sidebar', $node->field_image[0]['filepath'], $node->field_image[0]['data']['alt']).'</a></div>';
						}
                    	$output .= '<div class="lv-teaser-content">'.$node->field_teaser[0]['value'].'</div><div class="lv-teaser-link">'.l(t('Read more'), 'node/'.$node->nid).'</div></div>';                        
					}
				}                                
		    
              	$blocks['content'] = $output;
             	break;
            case 3:
				$blocks['subject'] = t("Spotlight on");            
				
				$result = db_query("SELECT n.nid, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 AND n.type = 'portrait' ORDER BY n.created DESC LIMIT 0,5");

				$output = '';
				while ($node = db_fetch_object($result)) {
					$node = node_load($node->nid);
	                $output .= '<div id="lv-teaser-'.$node->nid.'" class="lv-teaser"><h2>'.$node->title.'</h2>';
                    if (isset($node->field_image[0])) {
	   	                $output .= '<div class="lv-teaser-image"><a href="'.url('node/'.$node->nid).'">'.theme('imagecache', 'sidebar', $node->field_image[0]['filepath'], $node->field_image[0]['data']['alt']).'</a></div>';
					}
               	    $output .= '<div class="lv-teaser-content">'.$node->field_teaser[0]['value'].'</div><div class="lv-teaser-link">'.l(t('Read more'), 'node/'.$node->nid).'</div></div>';                        
				}                                
		    
              	$blocks['content'] = $output;
             	break;                
            } 
            return $blocks;
	}
}      


/**
 * Implementation of hook_theme().
 */
function lv_pages_theme($existing, $type, $theme, $path) {
	return array(
		'uc_catalog_latest' => array(
			'arguments' => array('tid' => NULL, 'lv_type' => NULL, 'sale_method' => NULL, 'account' => NULL, 'limit' => 10),
		    'file' => 'uc_catalog.pages.inc',            
            'path' => drupal_get_path('module', 'uc_catalog'),
		),
	);
}     


// PAGES

function lv_pages_front_page() {
	global $user;
	
	$output = '';
	
	if (!$user->uid) {

	    $output =  '
		    <h2 class="frontpage-welcome">Kom i gang med at handle</h2>	    
	    	 <p>
				For at købe eller sælge varepartier på Lagervarer.dk, skal du oprette en gratis brugerprofil. Du behøver ikke være momsregistreret eller have CVR-nummer.     
	    	 </p>
		     <p>
				Du kan sætte lige så mange varer og varepartier til salg, som du har lyst til. Det er helt gratis!     
		     </p>
	
			<div id="welcome-button" style="margin-top: 20px;">
	    	      <a class="linkbutton" href="'.url('user/register/business').'">Opret gratis bruger</a>
		    </div>
	    ';        
	
	}
	
	//$output .= '<div class="lv-catalog-latest"><h2>'.t('Top Auctions This Week').'</h2>'.theme('uc_catalog_browse', NULL, '', 'vareparti', '', 0, true).'</div><br />';
    //$output .= '<div style="clear: both; margin-top: 30px;"><a href="/lagersalg"><img src="/sites/all/themes/zenlager/images/knap-tilprivate.gif" /></a></div>';

    $output .= '<div class="lv-catalog-latest"><h2>'.lv_pages_more_link('catalog', t('View all consignments')).t('New consignments for sale').'</h2>'.theme('uc_catalog_latest').'<div class="lv-catalog-more">'.lv_pages_more_link('catalog', t('View all consignments')).'</div></div>';

	$output .= '<br /><br /><br /><div id="frontpage-welcome"><h2>Handelsplads hvor erhvervsfolk mødes</h2><p>
 <strong>Lagervarer.dk</strong> er stedet, hvor seriøse erhvervsfolk med sans for den gode handel mødes. Her kan du købe og sælge varepartier. Handel på Lagervarer.dk er helt GRATIS.
			</p><p>
<strong>Lagervarer.dk</strong> er dog ikke kun stedet, hvor du kan gøre en god handel. Det er også et forum, hvor du kan komme i kontakt med andre forretningsdrivende.
			</p><div><div id="frontpage-welcome-right"><img id="frontpage-welcome-image" src="/sites/all/themes/zenlager/images/frontPage1.jpg" />
            
            <div id="frontpage-types" class="block">   
				<h2 class="title">Sådan handler du</h2>        
    	        <div class="content">
                	<img src="/sites/all/themes/zenlager/images/ikon_auktion42.png" width="42" height="33" />
        		    <h3>Auktion</h3>
                    <p>Sæt dine varepartier på auktion og lad højest bydende købe</p>
	            </div>
    	        <div class="content">
                	<img src="/sites/all/themes/zenlager/images/ikon_givetbud42.png" width="42" height="33" />
        		    <h3>Prut om prisen</h3>
                    <p>Brugere kan frit byde på dit vareparti. Du kan acceptere buddet eller byde over.</p>
	            </div>
    	        <div class="content">
                	<img src="/sites/all/themes/zenlager/images/ikon_buynow42.png" width="42" height="33" />                
        		    <h3>Fast pris</h3>
                    <p>Du kan altid vælge at sætte dine varer til salg til fast pris.</p>
	            </div>            
        
	        </div>
            
            </div>

            <p>			   
<strong>Lagervarer.dk</strong> er først og fremmest for erhvervsdrivende, men private kan også kigge med. Så har du lyst til at sætte enkeltvarer til salg, er det også muligt. Du vil hurtigt opdage, at vi har tænkt os at blive kendt for at være et godt sted at handle – også for private.
    </p>
	
    <h2 class="frontpage-welcome">Kom i gang med at handle</h2>	    
     <p>
		For at købe eller sælge varepartier på Lagervarer.dk, skal du oprette en gratis brugerprofil. Du behøver ikke være momsregistreret eller have CVR-nummer.     
     </p>
     <p>
		Du kan sætte lige så mange varer og varepartier til salg, som du har lyst til. Det er helt gratis!     
     </p>

	<div id="welcome-button">
          <a class="linkbutton" href="'.url('user/register/business').'">Opret gratis bruger</a>
    </div>

        </div><div style="clear:both;"></div>
    
    </div>';


    return $output;
}        


function lv_pages_lagersalg_page() {
    $output = '<div class="lv-catalog-latest"><h2>'.t('All products for sale - newest on top').'</h2>'.theme('uc_catalog_browse', NULL, 'lagersalg', 'consumer').'</div>';
	$output .= '<br /><br /><div id="frontpage-welcome"><h2>Her kan alle være med</h2>
    
<div><div id="pages-welcome-right" style="width: 333px"><img src="/sites/all/themes/zenlager/images/frontPage2.jpg" />    
    <p>
<em>Finanskrisen er over os, men med <strong>Lagervarer.dk</strong> har du og andre private nu muligheden for at handle engros på lige fod med de erhvervsdrivende.</em></p></div>
<p>Nu får du muligheden for at handle til priser, som før krisen kun kunne opnås ved handel med store varepartier.</p><p>Vi er sikre på, du vil hurtigt vil opdage, at vi har tænkt os at blive kendt for at være et godt sted at handle &#8208; også for private.</p>
 


	
    <h2 class="frontpage-welcome">Kom i gang med at handle</h2>	    
     <p>
		Du behøver ikke oprette dig som bruger på <strong>Lagervarer.dk</strong> for at komme i gang med at handle. På denne side kan du se de nyeste varer, der er sat til salg. Du kan også gå på opdagelse i de forskellige kategorier. God fornøjelse!
     </p>

        </div><div style="clear:both;"></div>

    </div>';


	drupal_set_title('Lagersalg til private');
    return $output;


}   

function lv_pages_trim($string, $length, $break = ' &hellip;') {
	if (strlen($string) > $length) {
		$pos = strpos($string, " ", $length);
		$string = substr($string, 0, $pos) . $break;
	}

	return $string;
}


function lv_pages_more_link($url, $text = NULL, $extra_class = NULL) {
	$class = 'read-more';                     
    if (!$text) { $text = t('Read more'); }
	if ($extra_class) { $class .= ' '.$extra_class; }
	return '<a class="'.$class.'" href="'.url($url).'">'.$text.'<span> &raquo;</span></a>';


} 



function lv_pages_information() {

  drupal_set_title('Nyheder og aktuelt');
  
  $return = '';
  $result = db_query("SELECT nid FROM {node} WHERE type = 'story' AND status = 1 ORDER BY created DESC");
  while ($rs = db_fetch_array($result)) {
		$node = node_load($rs['nid']);
		$return .= theme('node', $node, true);
  }
 

 return $return;


}        


function lv_pages_forum() {
	
	// Latest forum topics
	$topics = lv_forum_get_topics(10, true);
	_advanced_forum_add_files();
	drupal_set_title(t('Forum')); 	
	$output = '<div id="forum"><div class="forum-top-links"><ul class="links forum-links"><li class="first">'.l(t('Show all forum topics'), 'forum/fora/alle').'</li><li class="last">'.l(t('Choose category'), 'forum').'</li></ul></div><h2>'.t('Latest forum posts').'</h2>' . theme('forum_topic_list', 0, $topics, 1, 10) . '</div>';

	// New users
	$output .= '<div><div class="forum-top-links"><ul class="links forum-links"><li class="first">'.l(t('Show all users'), 'brugere').'</li></ul></div><h2>'.t('New users').'</h2></div>'.lv_forum_user_list(false, 5, 2);


return $output;	
}    

