<?php
// $Id: uc_auction_as.install,v 1.1.2.1 2009/03/31 16:30:57 garrettalbright Exp $

/**
 * @file
 * Just another module installation file.
 *
 * @ingroup uc_auction_antisnipe
 */

/**
 * Implementation of hook_uninstall().
 */

function uc_auction_as_uninstall() {
	global $conf;
	foreach (array_keys($conf) as $key) {
		if (strpos($key, 'uc_auction_as') === 0) {
			variable_del($key);
		}
	}
}